---
title: "qualtricks"
author: "Launchpad McQuack"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```
- WIP
- supplements/piggybacks https://github.com/ropensci/qualtRics with user management stuff and site intercept stuff

## Installation
```{r, eval=FALSE}
devtools::install_github("derring-do/qualtricks")
```
* Optional: set up keys, urls, etc. in .Renviron

## Usage
```{r}
# Register your credentials using qualtricsR package
library(qualtRics)
qualtrics_api_credentials(api_key = Sys.getenv("QSI_TOKEN"),
                          base_url = Sys.getenv("QUALTRICS_BASE_URL"),
                          install = TRUE,
                          overwrite = TRUE)
library(qualtricks)
library(dplyr)
```

### Use qualtricsR for survey info

```{r, eval=FALSE}
# Get all survey names ----
surveys <- qualtRics::all_surveys()

head(surveys)

# Get all survey response counts ----
response_tables <- vector(mode = "list", length=nrow(surveys))

for(i in 1:length(response_tables)) {
  counts <- try(metadata(surveys$id[i], get=list(questions=FALSE, flow=FALSE, metadata=FALSE, responsecounts=TRUE))$responsecounts, silent=TRUE)
  if(class(counts) == "try-error") next
  counts$id = surveys$id[i]
  response_tables[[i]] <- counts
  message(i)
}

head(data.table::rbindlist(response_tables))
```
### Use qualtricks for user/admin operations and intercept stats
```{r}
library(qualtricks)
library(data.table)

# Organization info ---
getOrganization(organizationId=Sys.getenv("QUALTRICS_ORG_ID")) %>% names

# List all users ----
# listUsers(responseOnly=TRUE) # returns pre-processed HTTP response
listUsers(responseOnly=FALSE, offset = 100) %>% names

users <- lapply(seq(0,600,100), function(x) { listUsers(offset=x) }) %>% rbindlist
names(users)

# Get Intercept stats ----
# Need to scrape project IDs from UI because there's no API call to retrieve them
getProjectStats(projectId="SI_8iR8HS1JUSjlC85", Sys.Date()-365, Sys.Date(), dataType = "Impressions", interval="Month") %>% names
```

### Use qualtRics + qualtRics for user- and org-informed survey operations
```{r, eval=FALSE}
# Share surveys ----
receivingUser <- users$id[users$lastName=="Smith"][1] 
surveys$id[1:3] %>% purrr::map(., function(.) shareSurvey(userId = receivingUser, surveyId = .))

# Update surveys ----
# e.g. deactivate, rename
# TBD
```

